services:
  postgres:
    image: postgres:16-alpine
    command: ["postgres", "-c", "max_connections=200"]
    environment:
      POSTGRES_USER: vaultchat
      POSTGRES_PASSWORD: vaultchat
      POSTGRES_DB: vaultchat
    ports:
      - "5432:5432"
    volumes:
      - vaultchat_pg:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vaultchat"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  coturn:
    image: coturn/coturn:4.6.2
    ports:
      - "3478:3478/tcp"
      - "3478:3478/udp"
      - "5349:5349/tcp"
      - "5349:5349/udp"
    volumes:
      - ../turn/turnserver.conf:/etc/coturn/turnserver.conf:ro
    command: ["-c", "/etc/coturn/turnserver.conf"]

volumes:
  vaultchat_pg:
